import { NextResponse, type NextRequest } from 'next/server'
import { createServiceClient } from '@/lib/supabase/service'
import { getClientIp, isRateLimited } from '@/lib/rate-limit'

// Validates a secure upload token and returns the associated report info
export async function GET(request: NextRequest) {
  const ip = getClientIp(request)
  const rateKey = `/api/upload/secure-token:GET:${ip}`
  if (isRateLimited(rateKey, 10, 60_000)) {
    return NextResponse.json(
      { error: 'Too many requests. Please try again later.' },
      { status: 429 }
    )
  }

  const rawToken = request.nextUrl.searchParams.get('token')
  const token = rawToken?.trim()
  if (!token) {
    return NextResponse.json({ error: 'Token is required' }, { status: 400 })
  }

  let supabase
  try {
    supabase = createServiceClient()
  } catch {
    return NextResponse.json(
      { error: 'Upload service is not configured. Please contact support.' },
      { status: 503 }
    )
  }

  const { data } = await supabase
    .from('lab_reports')
    .select('id, patient_id, dietitian_id, token_expires_at, file_urls, upload_source, patients!inner(id, full_name, dietitian_id)')
    .eq('upload_token', token)
    .single()

  if (!data) {
    return NextResponse.json({ error: 'Invalid or expired token' }, { status: 404 })
  }

  const row = data as {
    id: string
    patient_id: string
    dietitian_id: string
    token_expires_at: string | null
    file_urls: string[]
    upload_source: 'patient' | 'dietitian'
    patients: { id: string; full_name: string; dietitian_id: string }
  }

  if (
    row.upload_source !== 'patient' ||
    row.patients.id !== row.patient_id ||
    row.patients.dietitian_id !== row.dietitian_id
  ) {
    return NextResponse.json({ error: 'Invalid upload link context' }, { status: 403 })
  }

  // Check expiry
  if (row.token_expires_at && new Date(row.token_expires_at) < new Date()) {
    return NextResponse.json({ error: 'This upload link has expired' }, { status: 410 })
  }

  // Check if already uploaded
  if (row.file_urls && row.file_urls.length > 0) {
    return NextResponse.json({ error: 'Report already uploaded via this link' }, { status: 409 })
  }

  return NextResponse.json({
    reportId: row.id,
    patientName: row.patients.full_name,
  })
}

// Patient uploads files via this token
export async function POST(request: NextRequest) {
  const ip = getClientIp(request)
  const rateKey = `/api/upload/secure-token:POST:${ip}`
  if (isRateLimited(rateKey, 10, 60_000)) {
    return NextResponse.json(
      { error: 'Too many requests. Please try again later.' },
      { status: 429 }
    )
  }

  const rawToken = request.nextUrl.searchParams.get('token')
  const token = rawToken?.trim()
  if (!token) {
    return NextResponse.json({ error: 'Token is required' }, { status: 400 })
  }

  let body: { file_paths: string[]; title?: string }
  try {
    body = (await request.json()) as { file_paths: string[]; title?: string }
  } catch {
    return NextResponse.json({ error: 'Invalid JSON body' }, { status: 400 })
  }

  if (!body.file_paths?.length) {
    return NextResponse.json({ error: 'At least one file path is required' }, { status: 400 })
  }

  // Accept only relative storage paths generated by server upload route.
  const validPath = (path: string) =>
    typeof path === 'string' &&
    path.length > 0 &&
    !path.includes('..') &&
    !path.startsWith('http://') &&
    !path.startsWith('https://')
  if (!body.file_paths.every(validPath)) {
    return NextResponse.json(
      { error: 'Invalid file paths. Files must be uploaded via the secure upload endpoint.' },
      { status: 400 }
    )
  }

  let supabase
  try {
    supabase = createServiceClient()
  } catch {
    return NextResponse.json(
      { error: 'Upload service is not configured. Please contact support.' },
      { status: 503 }
    )
  }

  // Find the report by token
  const { data: report } = await supabase
    .from('lab_reports')
    .select('id, dietitian_id, patient_id, token_expires_at, file_urls, upload_source, patients!inner(id, dietitian_id)')
    .eq('upload_token', token)
    .single()

  if (!report) {
    return NextResponse.json({ error: 'Invalid or expired token' }, { status: 404 })
  }

  const row = report as {
    id: string
    dietitian_id: string
    patient_id: string
    token_expires_at: string | null
    file_urls: string[]
    upload_source: 'patient' | 'dietitian'
    patients: { id: string; dietitian_id: string }
  }

  if (
    row.upload_source !== 'patient' ||
    row.patients.id !== row.patient_id ||
    row.patients.dietitian_id !== row.dietitian_id
  ) {
    return NextResponse.json({ error: 'Invalid upload source for token' }, { status: 403 })
  }

  if (row.token_expires_at && new Date(row.token_expires_at) < new Date()) {
    return NextResponse.json({ error: 'This upload link has expired' }, { status: 410 })
  }

  if (row.file_urls && row.file_urls.length > 0) {
    return NextResponse.json({ error: 'Report already uploaded' }, { status: 409 })
  }

  // Update report with uploaded files
  const { error } = await supabase
    .from('lab_reports')
    .update({
      file_urls: body.file_paths,
      title: body.title || 'Patient Upload',
      upload_token: null, // Consume the token
    })
    .eq('id', row.id)

  if (error) {
    return NextResponse.json({ error: error.message }, { status: 500 })
  }

  // Timeline event
  await supabase.from('timeline_events').insert({
    dietitian_id: row.dietitian_id,
    patient_id: row.patient_id,
    event_type: 'lab_report_uploaded' as const,
    event_data: { source: 'patient', title: body.title || 'Patient Upload' },
    reference_id: row.id,
  })

  return NextResponse.json({ success: true })
}
